### ISSUE TITLE
Add Quick Start

### ISSUE THREAD

**Issue by Brodan** [nicksam112/kanyec#2]
Any chance you can add a quickstart to the README so that I can compile this and write some kanyeC?

**Comment by nicksam112** [comment]
Sure thing, I'll get around to that as soon as my midterms are over

**Comment by Brodan** [comment]
Awesome, I just can't seem to figure out how to compile this locally after cloning the repo. Thanks!

**Comment by Brodan** [comment]
Any update on this?

**Comment by Brodan** [comment]
@nicksam112 any update on this?

**Comment by nicksam112** [comment]
I am so so sorry, I've just been completely swamped recently. 

I'll be posting an update to this before the end of the month, just need to get some personal things out of the way. Thank you for understanding!
